#+TITLE: Artificial Intelligence
#+SUBTITLE: Knowledge-Based AI
#+AUTHOR: Christopher Simpkins
#+INSTITUTE: Kennesaw State University
#+EMAIL:
#+DATE: Kennesaw State University
#+DESCRIPTION: Artificial Intelligence Knowledge-Based AI
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS: H:2 toc:nil num:t org-image-max-width:5in org-image-align:center
#+LaTeX_COMPILER: lualatex
#+LaTeX_HEADER: \usepackage[margin=1in]{geometry}
#+LaTeX_HEADER: \usepackage{fontspec}
#+LaTeX_HEADER: \usepackage{verbatim, multicol, tabularx,}
#+LaTeX_HEADER: \usepackage{amsmath, amsthm, amssymb, stmaryrd, latexsym, bm, listings, qtree}
#+LaTeX_HEADER: \usepackage{framed}
#+LaTeX_HEADER: \usepackage{xcolor,colortbl}
#+LaTeX_HEADER: \usepackage{media9}
#+LaTeX_HEADER: \usepackage[export]{adjustbox}
#+LaTeX_HEADER: \usepackage{algorithm}
#+LaTeX_HEADER: \usepackage[noend]{algpseudocode}
#+LaTeX_HEADER: \usepackage{tikz,pgfplots}
#+LaTeX_HEADER: \usetikzlibrary{shapes.geometric}
#+LaTeX_HEADER: \let\oldquote=\quote
#+LaTeX_HEADER: \let\endoldquote=\endquote
#+LaTeX_HEADER: \colorlet{shadecolor}{cyan!15}
#+LaTeX_HEADER: \renewenvironment{quote}{\begin{shaded*}\begin{oldquote}}{\end{oldquote}\end{shaded*}}
#+LaTeX_HEADER: % From https://tex.stackexchange.com/questions/7032/good-way-to-make-textcircled-numbers
#+LaTeX_HEADER: \newcommand*\circled[1]{\tikz[baseline=(char.base)]{\node[shape=circle,draw,inner sep=2pt] (char) {#1};}}
#+LaTeX_HEADER: \DeclareMathOperator*{\argmin}{arg\!min}
#+LaTeX_HEADER: \DeclareMathOperator*{\argmax}{arg\!max}
#+LaTeX_HEADER: \lstset{frame=tb, aboveskip=1mm, belowskip=0mm, showstringspaces=false, columns=flexible, basicstyle={\scriptsize\ttfamily}, numbers=left, frame=single, breaklines=true, breakatwhitespace=true}
#+LaTeX_HEADER: \hypersetup{colorlinks=true,urlcolor=blue}
#+LaTeX_HEADER: \usepackage{polyglossia}
#+LaTeX_HEADER: \setdefaultlanguage[variant=US]{english}

** Knowledge and AI

In AI, *knowledge-based* agents use a process of *reasoning* over an internal *representation* of knowledge to decide what actions to take.

- *Knowledge base*: a set of sentences.
- *Sentence*: an assertion about the world expressed in a *knowledge represeantation language*, like propositional logic.
- *Axioms*:  sentences taken as given -- not derived from other sentences, assumptions.
- *Inference*: deriving new sentences from old sentences.
- *Background knowledge*: sentences present in an agent's knowledge base before it starts perceiving and acting.

** Knowledge-Based Agents

- MAKE-PERCEPT-SENTENCE constructs sentence asserting that agent perceived the given percept at the given time.
- MAKE-ACTION-QUERY constructs sentence that asks what action  to take at current time.
- MAKE-ACTION-SENTENCE constructs sentence asserting chosen action was executed.


\begin{center}

#+latex: \includegraphics[alt={aima fig 07_01 kb agent},height=1in]{aima-fig-07_01-kb-agent.pdf}

\end{center}


- Logical agents are described at the *knowledge level* using *declarative* statements of knowledge and goals.
- At the *implemetation level* we use a *procedureal* approach, encoding behaviors directly in program code.


** The Wumpus World





\begin{center}

#+latex: \includegraphics[alt={aima fig 07_02 wumpus world},height=1in]{aima-fig-07_02-wumpus-world.pdf}

\end{center}







A cave that you can drop into or climb out of at square [1, 1].

- *Performance measure*: +1000 for climbing out of the cave with the gold, –1000 for falling into a pit or being eaten by the wumpus, –1 for each action taken, –10 for using the arrow. The game ends either when the agent dies or when the agent climbs out of the cave.




- *Environment*: A 4×4 grid of rooms, agent always starts at [1,1], facing east. Gold and the wumpus placed uniformly randomly from the squares other than the start square. Each non-start square can be a pit with probability 0.2.

- *Actuators*: Forward, TurnLeft by $90^\circ$, or TurnRight by $90^\circ$. The agent dies if it enters pit or a live wumpus square.  Moves into walls have no effect.  Grab picks up gold if agent in gold square. Shoot can fires arrow in direction agent is facing. The arrow continues until it either hits (and hence kills) the wumpus or hits a wall. The agent has only one arrow, so only the first Shoot action has any effect. Climb climbs out of the cave if at [1,1].

** First Steps Wumpus World

- *Sensors*: The agent has five sensors, each of which gives a single bit of information:

    - In squares directly (not diagonally) adjacent to wumpus, agent perceives a Stench.
    - In squares directly adjacent to a pit, the agent perceives a Breeze.
    - In the square with gold, agent perceives a Glitter.
    - When an agent walks into a wall, it perceives a Bump.
    - When the wumpus is killed, it emits a Scream perceivable anywhere in the cave.

Percepts encoded as list of five symbols indicating presense or absence (by None) of: [Stench,Breeze,Glitter,Bump,Scream] (a bit vector).



\begin{center}

#+latex: \includegraphics[alt={aima fig 07_03 first step wumpus world},height=1in]{aima-fig-07_03-first-step-wumpus-world.pdf}

\end{center}


- (a) after percept [None,None,None,None,None]
- (b) after moving to [2,1] and perceiving [None,Breeze,None,None,None]

** Logic

Basics:

- *Syntax* specifies the form of sentences.

    - $x + y = 4$ is *well-formed*, but $x4y+=$ is not.

- *Semantics* specifies the meaning of sentences.

    - $x + y = 4$ is *true* in a world where $x = 1$ and $y = 3$.

- *Model*: a formal specification of a *possible world*, that is, a set of assignments of values to the variables in the sentences of a knowledge base.

    - Given a model {$x = 3$, $y = 2$}, the sentence $x + y = 4$ is false.

Satisfaction:

- "$m$ satisfies $\alpha$": sentence $\alpha$ is true in model $m$, also "$m$ is a model of $\alpha$."
- $M(\alpha)$ the set of all models of $\alpha$, i.e., the set of all models in which $\alpha$ is true.

Entailment: $\alpha \models \beta$: $\beta$ *follows logically* from $\alpha$

Formal definition of entailment:

\begin{equation*}
\alpha \models \beta \text{ if and only if } M(\alpha) \subseteq M(\beta)
\end{equation*}

** Possible Models of Pits in Wumpus World

The presence of pits in squares [1, 2], [2, 2] and [3, 1] gives rise to $2^3 = 8$ possible models.


\begin{center}

#+latex: \includegraphics[alt={aima fig 07_05 possible models pits},height=1in]{aima-fig-07_05-possible-models-pits.pdf}

\end{center}


Solid line delineates KB based on percept [None, None, None, None, None] in [1, 1] and [None,Breeze,None,None,None] in [2, 1].

- (a). $\alpha_1$ = "There is no pit in [1, 2]."  Here, $KB \models \alpha_1$
- (b). $\alpha_2$ = "There is no pit in [2, 2]."  Here, $KB \nvDash \alpha_2$

Logical inference via model checking: because of (b), cannot conclude $\alpha_2$ (or $\neg \alpha_2$).

- $M(KB) \models \alpha_1$ but  $M(KB) \nvDash \alpha_2$

** Inference Algorithms

If an inference algorithm $i$ can derive $\alpha$ from $KB$, we write

\begin{equation*}
KB \vdash_i \alpha
\end{equation*}

which is pronounced "$\alpha$ is derived from $KB$ by $i$" or "$i$ derives $\alpha$ from $KB$."

*Important properties of inference algorithms*:

- An inference algorithm that derives only entailed sentences is called *sound* or *truth-preserving*.

- An inference algorithm is *complete* if it can derive any sentence that is entailed.

** Representation vs World

If KB is true in the real world, then any sentence $\alpha$ derived from KB by a sound inference procedure is also true in the real world?


\begin{center}

#+latex: \includegraphics[alt={aima fig 07_06 representation vs world},height=1in]{aima-fig-07_06-representation-vs-world.pdf}

\end{center}


*Grounding*: connection between logical reasoning and the real environment.  How do we know that KB is true in the real world.

- Subject of volumes of philosophical investigation.
- For us: if agent perceives it, it is true.

** Propositional Logic

- *Atomic* sentences consist of a single proposition symbol.
- Proposition symbol stands for a proposition that can be true or false.

    - We use symbols that start with uppercase letter and may contain other letters or subscripts, e.g., : P, Q, R, $W_{1,3}$ and FacingEast
    - True and False have fixed meanings

- *Complex sentence*: one or more atomic sentences constructed from *logical connectives*.

- $\neg$ (not) Unary connective.  $\neg W_{1,3}$ is the *negation* of $W_{1,3}$

    - A *positive literal* is an atomic sentence.
    - a *negative literal* is a negated atomic sentence.

- $\land$ (and).  Binary connective.  *Conjunction*, e.g., $W_{1,3} \land P_{3,1}$

- $\lor$ (or).  Binary connective.  *Disjunction*, e.g., $(W_{1,3} \land P_{3,1}) \lor W_{2,2}$

- $\implies$ (implies).  Binary connective.  *Implication*, e.g., $(W_{1,3} \land P_{3,1}) \implies \neg W_{2,2}$

    - $(W_{1,3} \land P_{3,1})$ is the *premise* or *antecedent*.
    - $\neg W_{2,2}$ is the *conclusion* or *consequent*.
    - Also known as rules or if-then statements.
    - Some authors use $\supset$ or $\rightarrow$

- $\iff$ (if and only if).  Binary connective. $W_{1,3} \iff \neg W_{2,2}$ is a *biconditional*

** Grammar of Propositional Logic


\begin{center}

#+latex: \includegraphics[alt={aima fig 07_07 grammar of popositional logic},height=1in]{aima-fig-07_07-grammar-of-popositional-logic.pdf}

\end{center}


** Semantics of Propositional Logic


\begin{center}

#+latex: \includegraphics[alt={aima fig 07_08 truth tables logical connectives},height=1in]{aima-fig-07_08-truth-tables-logical-connectives.pdf}

\end{center}


** Propositional Theorem Proving

So far we've done *model checking*: enumerating models and showing that the sentence must hold in all models.

Now we turn to *theorem proving*: applying rules of inference directly to the sentences in our knowledge base to construct a proof of the desired sentence without consulting models.

Some basic concepts:

- *Logical equivalence*: two sentences $\alpha$ and $\beta$ are logically equivalent if they are true in the same set of models.  $\alpha \equiv \beta$

    - $\alpha \equiv \beta$ if and only if $\alpha \models \beta$ and $\beta \models \alpha$

- *Validity*: A sentence is valid if it is true in all models. For example, the sentence $P \land \neg P$ is valid. Valid sentences are also known as *tautologies*.

- *Deduction theorem*: $\text{For any sentences $\alpha$ and $\beta$ }, \alpha \models \beta \text{ if and only iff the sentence } (\alpha \implies \beta) \text{ is valid.}$

- A sentence is *satisfiable* if it is true in, or satisfied by, *some* model

** Inference Rules

General form:

\begin{equation*}
\frac{Givens}{Conclusions}
\end{equation*}


Modus Ponens:

\begin{equation*}
\frac{\alpha \implies \beta, \alpha}{\beta}
\end{equation*}

And-Elimination:

\begin{equation*}
\frac{\alpha \land \beta}{\alpha}
\end{equation*}

** Logical Equivalences

Functionally equivalent to inference rules.  Left side on top, right side on bottom.


\begin{center}

#+latex: \includegraphics[alt={aima fig 07_11 logical equivalences},height=1in]{aima-fig-07_11-logical-equivalences.pdf}

\end{center}



** Representational Power of Formal Languages

- Propositional logic assumes that there are facts that either hold or do not hold in the world. Each fact can be in one of two states—true or false—and each model assigns true or false to each proposition symbol.
- First-order logic assumes that the world consists of objects with certain relations among them that do or do not hold.


\begin{center}

#+latex: \includegraphics[alt={aima fig 08_01 ontological epistemological commitments},height=1in]{aima-fig-08_01-ontological-epistemological-commitments.pdf}

\end{center}


- *Ontological commitment*: what a language assumes about the nature of reality.
- *Epistemological commitments*: the possible states of knowledge a language allows with respect to each fact.

*Sapir-Whorf Hypothesis*: you can only think things you can express in a language you know.

** Representational Power of First-Order Logic


\begin{center}

#+latex: \includegraphics[alt={aima fig 08_02 person king model},height=1in]{aima-fig-08_02-person-king-model.pdf}

\end{center}


** First-Order Logic

Also known as first-order predicate logic.

- *Constant symbols* stand for objects, e.g., $Richard$, $John$.

- *Predicate symbols* stand for relations, e.g., $Brother(Richard, John)$.

- *Function symbols* stand for functions, e.g., $LeftLeg(John)$

    - Above is also a *term* -- a logical expression that refers to an object.

Atomic sentences:

- $Brother(Richard, John)$, $Married(Father(Richard),Mother(John))$

Complex sentences:

- $Brother(Richard,John) \land Brother(John,Richard)$

Quantifiers:

- $\forall x, King(x) \implies Person(x)$

    - For all objects $x$, if $x$ is a $King$, then $x$ is a $Person$.
    - In English:"All kings are persons."
- $\exists x, Crown(x) \land Onhead(x, John)$

    - There exists an $x$ such that $x$ is a $Crown$ and $x$ is on the head of $John$.
    - In English: "John has a crown on his head."

** Knowledge Representation

Complex reasoning requires representation of abstract concepts:

- Events
- Time
- Physical Objects
- Beliefs

Representing abstract concepts is sometimes called *ontological engineering*.

** Physical Objects

- Categories vs objects

    - A category is a set which represents some commonality among objects in the set.
    - Individuation: division into distinct objects

- Part vs whole

    - Composites represent structural relationships between parts
    - $Biped(a) \implies \exists l_1, l_2, b, Leg(l_1) \land Leg(l_2) \land Body(b) \land PartOf(l_1, b) \dots$

- Measures

    - Kind of quantity, e.g., length, weight, mass
    - Units, conversions

- Count nouns vs mass nouns

    - Count noun: 2 glass*es* of water -- 1 glass is *FEWER* than 2 glasses

    - Mass noun: a gallon of water -- 1 gallon is *LESS THAN* 2 gallons

- Intrinsic vs extrinsic properties

    - Intrinsic properties part of essence of object
    - Extrinsic properties are not retained under subdivision
    - Gold still glitters when split into two equal parts, but each part now has half the mass, weight.

** Categories and Objects

Two choices for representing a category:

- use *predicates*, like $Basketball(b)$, or
- *reify* the category as an object itself and say

    - $Member(b,Basketballs)$ or $b \in Basketballs$.

Can also have subcategories, e.g., $Subset(Basketballs,Balls)$ or $Basketballs \subset Balls$.

Categories organize knowledge into *inheritance hierarchies*, or *taxonomies*, like this upper ontology of the world:


\begin{center}

#+latex: \includegraphics[alt={aima fig 10_01 upper ontology world},height=1in]{aima-fig-10_01-upper-ontology-world.pdf}

\end{center}



** Events and Time

An *event calculus* encodes events, fluents, and time points, and the relationships between them.

- A *fluent* is an aspect of the world that changes, an object that changes over time.
- An *event* is a temporal, locational, or relational fixing of object(s).

    - $E_1 \in Flyings \land Flyer(E_1,Shankar) \land Origin(E_1,SF) \land Destination(E_1,DC)$

- A *time predicate*, $T$, fixes a fluent or event in time, e.g.,

    - $T(f, t_1, t_2)$ Fluent $f$ is true for all times between $t_1$ and $t_2$
    - $Happens(e,t1,t2)$ Event $e$ starts at time $t_1$ and ends at $t_2$


\begin{center}

#+latex: \includegraphics[alt={aima fig 10_02 predicates time intervals},height=1in]{aima-fig-10_02-predicates-time-intervals.pdf}

Predicates on time intervals.
\end{center}


** Fluents


\begin{center}

#+latex: \includegraphics[alt={aima fig 10_03 schematic object president},height=1in]{aima-fig-10_03-schematic-object-president.pdf}

\end{center}


$
T(Equals(President(USA),GeorgeWashington),Begin(AD1789),End(AD1797))
\begin{equation*}

Use $Equals$ function instead of logical predicate $=$ because can't have have predicate as argument to $T$.


## Beliefs and Attitudes


Beliefs are mental objects. Consider

\end{equation*}
Knows(Lois,CanFly(Superman))
\begin{equation*}

What if Lois knows that Clark Kent is Superman?

```{=latex}
\begin{align*}
& (Superman = Clark) \land Knows(Lois,CanFly(Superman)) \\
& \hspace{.2in} \models Knows(Lois,CanFly(Clark))
\end{align*}
```

This gets out of hand quickly.  Need **modal logic**, which includes modal operators that take sentences as arguments instead of terms.  $A$ knows $P$ becomes:

\end{equation*}
\bm{K}_A P
\begin{equation*}

Where $\bm{K}$ is the modal operator for knowledge.  First argument $A$ is the agent and written as subscript.  Second argument, $P$, is the proposition that $A$ "knows."

## Semantic Networks

Originally called **existential graphs**.

```{=latex}
\begin{center}
```
![](aima-fig-10_04-semantic-network-4-objects.pdf){height="60%"}
```{=latex}
\end{center}
```

## Closing Thoughts

- **Much** more to knowledge-based AI than presented here
- This overview enough to feel confident discussing knowledge-based AI at cocktail parties
- Knowledge-based AI heart of *expert systems*, failure of which led to an AI winter

    - Knowledge-acquisition bottleneck hindered completeness

        - Practically impossible for a physician to encode his/her medical knowledge in rules.

    - Knowledge AI fell out of favor, has never really recovered the mantle of AI

        - Didn't stop Doug Lennat and his team at [Cycorp](https://cyc.com/) from trying.
