#+TITLE: Artificial Intelligence
#+SUBTITLE: Nondeterministic Search
#+AUTHOR: Christopher Simpkins
#+INSTITUTE: Kennesaw State University
#+EMAIL:
#+DATE: Kennesaw State University
#+DESCRIPTION: Artificial Intelligence Nondeterministic Search
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS: H:2 toc:nil num:t org-image-max-width:5in org-image-align:center
#+LaTeX_COMPILER: lualatex
#+LaTeX_HEADER: \usepackage[margin=1in]{geometry}
#+LaTeX_HEADER: \usepackage{fontspec}
#+LaTeX_HEADER: \usepackage{verbatim, multicol, tabularx,}
#+LaTeX_HEADER: \usepackage{amsmath, amsthm, amssymb, stmaryrd, latexsym, bm, listings, qtree}
#+LaTeX_HEADER: \usepackage{framed}
#+LaTeX_HEADER: \usepackage{xcolor,colortbl}
#+LaTeX_HEADER: \usepackage{media9}
#+LaTeX_HEADER: \usepackage[export]{adjustbox}
#+LaTeX_HEADER: \usepackage{algorithm}
#+LaTeX_HEADER: \usepackage[noend]{algpseudocode}
#+LaTeX_HEADER: \usepackage{tikz,pgfplots}
#+LaTeX_HEADER: \usetikzlibrary{shapes.geometric}
#+LaTeX_HEADER: \let\oldquote=\quote
#+LaTeX_HEADER: \let\endoldquote=\endquote
#+LaTeX_HEADER: \colorlet{shadecolor}{cyan!15}
#+LaTeX_HEADER: \renewenvironment{quote}{\begin{shaded*}\begin{oldquote}}{\end{oldquote}\end{shaded*}}
#+LaTeX_HEADER: % From https://tex.stackexchange.com/questions/7032/good-way-to-make-textcircled-numbers
#+LaTeX_HEADER: \newcommand*\circled[1]{\tikz[baseline=(char.base)]{\node[shape=circle,draw,inner sep=2pt] (char) {#1};}}
#+LaTeX_HEADER: \DeclareMathOperator*{\argmin}{arg\!min}
#+LaTeX_HEADER: \DeclareMathOperator*{\argmax}{arg\!max}
#+LaTeX_HEADER: \lstset{frame=tb, aboveskip=1mm, belowskip=0mm, showstringspaces=false, columns=flexible, basicstyle={\scriptsize\ttfamily}, numbers=left, frame=single, breaklines=true, breakatwhitespace=true}
#+LaTeX_HEADER: \hypersetup{colorlinks=true,urlcolor=blue}
#+LaTeX_HEADER: \usepackage{polyglossia}
#+LaTeX_HEADER: \setdefaultlanguage[variant=US]{english}

** Nondeterministic Search (AIMA 4.3-4.5)

So far we've learned about search in fully observable, deterministic, known environments.  In this lesson we consider:

- environments with nondeterministic actions,
- partially observable environments, and
- unknown environments.

# Search with Nondeterministic Actions

** Nondeterministic Actions: The Erratic Vacuum World




In the erratic vacuum world, the Suck action works as follows:

- When applied to a dirty square the action cleans the square and sometimes cleans up dirt in an adjacent square, too.
- When applied to a clean square the action sometimes deposits dirt on the carpet.

So the result of each action is a set, e.g.:

\begin{equation*}
\text{Results}(1,Suck) = \{5, 7\}
\end{equation*}

That set of states that the agent believes is possible, {5, 7}, is called a *belief state*.





#+latex: \includegraphics[alt={aima fig 04_09 vacuum states},width=0.75\linewidth]{aima-fig-04_09-vacuum-states.pdf}






** A Factored Representation

Let's depart from the book for a few slides and, instead of using an index into a vector of states, create a factored representation for clarity.

- `left-condition` $\in$ {~CLEAN~, ~DIRTY~}
- `right-condition` $\in$ {~CLEAN~, ~DIRTY~}
- `vacuum-location` $\in$ {~LEFT~, ~RIGHT~}
- State representation: `<vacuum-location, left-condition, right-condition>`

So


`Results(1,Suck) = {5, 7}`

becomes

`Results(<LEFT, DIRTY, DIRTY>, Suck) = {<LEFT, CLEAN, DIRTY>, <LEFT, CLEAN, CLEAN>}`


Note that the factored representation is easier for us to read (don't have to look up states in a table), but the search algorithms we're considering here treat these states as atomic.

** Conditional Plans

A conditional plan, a.k.a. *contingency plan*, is a plan that specifies action selection based on the observed state while executing the plan.

- In a fully-observable, deterministic world contingencies are not necessary -- a plan is just a sequence of actions.
- We need conditional/contingency plans in environments that are partially observable or nondeterministic.

Consider the start state, `<LEFT, DIRTY, DIRTY>`.  Due to the environment's nondeterminism, not possible to find a sequence of actions guaranteed to solve the problem.  But this simple conditional plan does:


`[Suck, if State == <LEFT, CLEAN, DIRTY> then [Right, Suck] else []]`



** AND-OR Search Trees




- Branch on agent's action: *OR nodes*, shown as states.
- Branch on environment's outcome: *AND nodes*, shown as circles with arc linking branches to possible outcome states (when > 1).
- A plan includes actions for OR nodes, and conditional actions for AND nodes that contain more than one state.

Trace this conditional plan through the tree on the right.

`[Suck,`
`if State == <LEFT, CLEAN, DIRTY> then [Right, Suck]`
`else []]`





#+latex: \includegraphics[alt={aima fig 04_10 vacuum and or search tree},height=3.6in]{aima-fig-04_10-vacuum-and-or-search-tree.pdf}






** Slippery Vacuum World




- Like deterministic vacuum world, but a movement action may result in no movement.


`Results(<LEFT, DIRTY, DIRTY>, Right) =`
`    {<LEFT, DIRTY, DIRTY>, <RIGHT, DIRTY, DIRTY>}`


- Do deal with nondetermnistic movements we need cyclic plans.  Use a *while* construct:


`[Suck,`
` while State == <LEFT, CLEAN, DIRTY> do Right,`
` Suck]`






#+latex: \includegraphics[alt={aima fig 04_12 slippery vacuum search graph},height=3.6in]{aima-fig-04_12-slippery-vacuum-search-graph.pdf}






# Search in Partially Observable Environments

** Search in Sensorless Environments





Now let's turn to uncertainty in the state observations, first with a sensorless world.

Sensorless, a.k.a. conformant, problems are surprisingly common.

- Manufacturing: orienting parts regardless of initial position.
- Medicine: applying broadly applicable treatments without running tests.

Consider a sensorless version of the (deterministic) vacuum world. Assume that the agent knows the geography of its world, but not its own location or the distribution of dirt.

Given an initial belief state is {1,2,3,4,5,6,7,8}.

- After [Right], belief state is {2,4,6,8}
- After [Right,Suck] belief state is {4,8}.
- After [Right,Suck,Left,Suck], belief state is {7}.

We say that the agent can *coerce* the world into state 7.





#+latex: \includegraphics[alt={aima fig 04_09 vacuum states},width=0.75\linewidth]{aima-fig-04_09-vacuum-states.pdf}






** Search Algorithms for Sensorless Environments

Instead of creating new algorithms, we transform the original problem into a belief state problem.

The original problem, $P$, has components $Actions_P$, $Result_P$ etc., and the belief-state problem has the following components:

- *States*: The belief-state space contains every possible subset of the physical states. If $P$ has $N$ states, then the belief-state problem has $2^N$ belief states, although many of those may be unreachable from the initial state (see next slide).

- *Initial state*: Typically the belief state consisting of all states in $P$, although in some cases the agent will have more knowledge than this.

- *Actions*: $Actions(b) = \bigcup_{s \in b} Actions_P(s)$ or $Actions(b) = \bigcap_{s \in b} Actions_P(s)$

- *Transition model*: For deterministic actions, the new belief state has one result state
for each of the current possible states.  With nondeterminism, the new belief state consists of all the possible results of applying the action to any of the states in the current belief state.

- *Goal test*.  We aim to *necessarily* achieve the goal.

    - The agent *possibly* achieves the goal if $\exists s \in b : IsGoal_P(s)$.
    - The agent *necessarily* achieves the goal if $\forall s \in b : IsGoal_P(s)$.

- *Action cost*: If the same action can have different costs in different states, then the cost of taking an action in a given belief state could be one of several values. For now we assume that the cost of an action is the same in all states and so can be transferred directly from the underlying physical problem.

** Reachable States in Sensorless Vacuum World

Only 12 reachable belief states out of $2^8 = 256$ possible belief states.





#+latex: \includegraphics[alt={aima fig 04_14 reachable sensorless vacuum belief states},height=3.2in]{aima-fig-04_14-reachable-sensorless-vacuum-belief-states.pdf}






#+latex: \includegraphics[alt={aima fig 04_09 vacuum states},width=0.75\linewidth]{aima-fig-04_09-vacuum-states.pdf}






** Actions in Sensorless Environments

- *Actions*: If $b = \{s_1,s_2\}$, but $Actions_P(s_1) \ne Actions_P(s_2)$; then agent can't be sure which actions are legal. If illegal actions have no effect, safe to take union of all  actions in the current belief state $b$:

\begin{equation*}
Actions(b) = \bigcup_{s \in b} Actions_P(s)
\end{equation*}

If an illegal action might lead to catastrophe, safer to allow only the intersection -- set of actions legal in all states. For the vacuum world, every state has the same legal actions, so both methods give the same result.

** Transition Model in Sensorless Environments

- *Transition model*: For deterministic actions, the new belief state has one result state
for each of the current possible states (although some result states may be the same):

\begin{equation*}
b' = Result(b,a) = \{s': s' = Result_P(s,a) \text{ and } s \in b\}
\end{equation*}

With nondeterminism, the new belief state consists of all the possible results of applying the action to any of the states in the current belief state:

\begin{align*}
b'= Results(b,a) &= \{s': s' \in Results_P(s,a) and s \in b\}\\
                 &= \bigcup_{s \in b} Results_P(s,a)
\end{align*}

The size of $b'$ will be the same or smaller than b for deterministic actions, but may be larger than $b$ with nondeterministic actions.


** Predicting Belief States in Sensorless Deterministic Vacuum World

Apply the deterministic action to all states in $b$ to get $b'$.


#+latex: \includegraphics[alt={aima fig 04_13_a sensorless vacuum belief state deterministic actions},width=0.75\linewidth]{aima-fig-04_13_a-sensorless-vacuum-belief-state-deterministic-actions.pdf}




\begin{align*}
b' = Result(b,a)             &= \{s': s' = Result_P(s,a) \text{ and } s \in b\}\\
b' = Result(\{1, 3\}, Right) &= \{ Result_P(1,Right), Result_P(3,Right) \}\\
                             &= \{2, 4\}
\end{align*}

** Predicting Belief States in Sensorless Slippery Vacuum World

Apply the nondeterministic action to all states in $b$ to get $b'$.


#+latex: \includegraphics[alt={aima fig 04_13_b sensorless vacuum belief state nondeterministic actions},width=0.75\linewidth]{aima-fig-04_13_b-sensorless-vacuum-belief-state-nondeterministic-actions.pdf}



\begin{align*}
b'= Results(b,a)             &= \bigcup_{s \in b} Results_P(s,a)\\
b' = Result(\{1, 3\}, Right) &= \bigcup_{s \in \{1, 3\}} Results_P(s,Right)\\
b' = Result(\{1, 3\}, Right) &= Result_P(1,Right) \cup Result_P(3,Right)\\
                             &= \{1, 2\} \cup \{4, 3\}\\
                             &= \{1, 2, 4, 3\}
\end{align*}

** Search in Partially Observable Environments

Many problems cannot be solved without sensing, e.g., sensorless 8-puzzle is impossible.

We can solve 8-puzzles if we can see just the upper-left corner square by moving each tile in turn into the observable square and keeping track of its location from then on.

For a partially observable problem, the problem specification will specify a $Percept(s)$ function that returns the percept received by the agent in a given state.

- For nondeterministic sensing, $Percepts(s) = \{s\}_{s \in S}$
- For fully observable problems, $\forall s, Percept(s) = s$
- For sensorless problems $Percept(s) = \text{null}$.

** Local-Sensing Vacuum World




The agent has a position sensor that yields the percept L in the left square, and R in the right square, and a dirt sensor that yields Dirty when the current square is dirty and Clean when it is clean -- but does not sense the other square.  This is nondeterministic sensing becuase the same percept can match more than one state:

- The PERCEPT in State 1 is [L,Dirty].
- State 3 will also produce [L,Dirty].
- Hence, the initial belief state will be {1,3}:

    - $Percepts(1) = \{1, 3\}$

How do we algorithmically get that belief state ...





#+latex: \includegraphics[alt={aima fig 04_09 vacuum states},width=0.75\linewidth]{aima-fig-04_09-vacuum-states.pdf}







** Transition Model in Partially Observable Environments

After we apply an action in a given belief state, we can think of the transition model between belief states for partially observable problems as occurring in three stages, as depicted in the next slide:

- The *prediction* stage computes the belief state resulting from the action, Result(b,a), exactly as we did with sensorless problems. To emphasize that this is a prediction, we use the notation $\hat{b} = Result(b,a)$, where the hat over the $b$ means "estimated," and we also use Predict(b,a) as a synonym for Result(b,a).

- The *possible percepts* stage computes the set of percepts that could be observed in the
predicted belief state (using the letter o for observation):

\begin{equation*}
PossiblePercepts(\hat{b}) = \{o : o = Percept(s) \text{ and } s \in \hat{b}\}
\end{equation*}

- The *update* stage computes, for each possible percept, the belief state that would result from the percept. The updated belief state $b_o$ is the set of states in $\hat{b}$ that could have
produced the percept:

\begin{equation*}
b_o = Update(\hat{b},o) = \{s : o = Percept(s) \text{ and } s \in \hat{b}\}
\end{equation*}

** State Transitions with Local Sensing (Summary)




#+latex: \includegraphics[alt={aima fig 04_15 local sensing vacuum state transitions},width=0.75\linewidth]{aima-fig-04_15-local-sensing-vacuum-state-transitions.pdf}






1. Predict $\hat{b} = Result(b, a)$
\begin{multline*}
\text{2. } PossiblePercepts(\hat{b}) = \\
\{o : o = Percept(s) \text{ and } s \in \hat{b}\}
\end{multline*}
\begin{multline*}
\text{3. } b_o = Update(\hat{b},o) = \\
\{s : o = Percept(s) \text{ and } s \in \hat{b}\}
\end{multline*}


Final column on left shows input to Update step, which will then compute the final $b_o$ based on percept/observation $o$.

- (a) Deterministic world.
- (b) Slippery world. Input to Update step are 3 belief states, each of which is no larger than the belief state from which they were produced.





** State Transitions with Local Sensing and Deterministic Actions




1. Predict:
\vspace{-.25in}
\begin{align*}
\hat{b} &= Result(b, a)\\
        &= Result(\{1, 3\}, Right)\\
        &= \{2, 4\}
\end{align*}

2. Possible percepts:
\vspace{-.25in}
\begin{align*}
PossiblePercepts(\hat{b})  &= \{o : o = Percept(s) \text{ and } s \in \hat{b}\}\\
PossiblePercepts(\{2, 4\}) &= \{o : o = Percept(s) \text{ and } s \in \{2, 4\}\}\\
                           &= \{[R, Dirty], [R, Clean]\}
\end{align*}





#+latex: \includegraphics[alt={aima fig 04_15_a local sensing vacuum deterministic state transitions},width=0.75\linewidth]{aima-fig-04_15_a-local-sensing-vacuum-deterministic-state-transitions.pdf}






Then the two belief states on the right are then fed to the final step once the agent gets a percept.  If the percept is $[R, Dirty]$, then:

3. Update:
\vspace{-.25in}
\begin{align*}
b_o &= Update(\hat{b},o) = \{s : o = Percept(s) \text{ and } s \in \hat{b}\}\\
    &= Update(\{[R, Dirty], [R, Clean]\}) = \{s : o = Percept(s) \text{ and } s \in \hat{b}\}\\
    &= \{2\}
\end{align*}

** State Transitions with Local Sensing in Slippery Vacuum World




1. Predict:
\vspace{-.25in}
\begin{align*}
\hat{b} &= Result(b, a)\\
        &= Result(\{1, 3\}, Right)\\
        &= \{2, 1, 3, 4\}
\end{align*}

2. Possible percepts:
\vspace{-.25in}
\[
PossiblePercepts(\hat{b}) = \{o : o = Percept(s) \text{ and } s \in \hat{b}\}
\]
\vspace{-.4in}
\begin{multline*}
PossiblePercepts(\{2, 1, 3, 4\}) = \\
    \{o : o = Percept(s) \text{ and } s \in \{2, 1, 3, 4\}\} =\\
    \{[R, Dirty], [L, Dirty], [L, Dirty], [R, Clean]\}
\end{multline*}






#+latex: \includegraphics[alt={aima fig 04_15_b local sensing vacuum nondeterministic state transitions},height=2.0in]{aima-fig-04_15_b-local-sensing-vacuum-nondeterministic-state-transitions.pdf}






Then the three belief states on the right are then fed to the final step once the agent gets a percept.  If the percept is $[L, Dirty]$, then:

3. Update:
\vspace{-.25in}
\begin{align*}
b_o &= Update(\hat{b},o) = \{s : o = Percept(s) \text{ and } s \in \hat{b}\}\\
    &= Update(\{[R, Dirty], [L, Dirty], [L, Dirty], [R, Clean]\}) = \{s : o = Percept(s) \text{ and } s \in \hat{b}\}\\
    &= \{1, 3\}
\end{align*}



** Planning Time State Estimation

The agent needs to deal with possible percepts at planning time, because it won’t know the actual percepts until it executes the plan.

- Nondeterminism in the physical environment can enlarge the belief state in the prediction stage, but each updated belief state $b_o$ can be no larger than the predicted belief state $\hat{b}$; observations can only help reduce uncertainty.
- For deterministic sensing, the belief states for the different possible percepts will be disjoint, forming a partition of the original predicted belief state.

Putting the three stages from previous slide together, we obtain the possible belief states resulting from a given action and the subsequent possible percepts:

\begin{equation*}
Results(b,a) = \{b_o : b_o = Update(Predict(b,a),o) \text{ and }
    o \in PossiblePercepts(Predict(b,a))\}.
\end{equation*}



** Belief State Maintenance in Partially Observable Environments

Kindergarten world (square not being actively cleaned can become dirty):

#+latex: \includegraphics[alt={aima fig 04_17 vacuum prediction update cycles},width=0.75\linewidth]{aima-fig-04_17-vacuum-prediction-update-cycles.pdf}



- Most real-world environments partially observable.  Belief state maintenance is core task.
- Also known as *monitoring*, *filtering*, and *state estimation*.

\begin{equation*}
b' = Update(Predict(b,a),o).
\end{equation*}

Equation above is called a recursive state estimator because it computes the new belief state from the previous one rather than by examining the entire percept sequence.


** Robot Localization

Localization: typical robot state estimation problem in which the robot works out where it is, given a map of the world and a sequence of percepts and actions.


#+latex: \includegraphics[alt={aima fig 04_18 robot localization},height=2.4in]{aima-fig-04_18-robot-localization.pdf}



** Online Seach

- Agents we've studied so far use *offline search* algorithms, which compute a complete solution before taking first action.
- *Online search* agents interleave computation and action.

    - Good in dynamic environments where computation time must be limited so environment doesn't change while the agent computes an action.
    - Good in nondeterministic environments so agent can focus on contingencies that actually arise.
    - In unkown environments, agent must act in order to learn about the environment.
    - Tradeoff: more planning can prevent ending up in dead ends.

Canonical example of online search: mapping problem.  Agent placed in unknown environment and must explore to build a map.

- The problem of doing localization and mapping at the same time is called *SLAM*: Simultaneous Localization and Mapping.

