#+TITLE: Enhanced Entity-Relationship Models
#+AUTHOR:
#+EMAIL:
#+DATE:
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS: H:2 toc:nil num:t ^:{}
#+BEAMER_FRAME_LEVEL: 2
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [smaller]
#+LaTeX_HEADER: \usepackage{verbatim, multicol, tabularx,}
#+LaTeX_HEADER: \usepackage{amsmath,amsthm, amssymb, latexsym, listings, qtree}
#+LaTeX_HEADER: \lstset{frame=tb, aboveskip=1mm, belowskip=0mm, showstringspaces=false, columns=flexible, basicstyle={\scriptsize\ttfamily}, numbers=left, frame=single, breaklines=true, breakatwhitespace=true}
#+LaTeX_HEADER: \setbeamertemplate{footline}[frame number]
#+LaTeX_HEADER: \hypersetup{colorlinks=true,urlcolor=blue}
#+LaTeX_HEADER: \logo{\includegraphics[height=.75cm]{GeorgiaTechLogo-black-gold.png}}

* Enhanced Entity-Relationship Models

** Enahnced Entity-Relationship Models

Enhanced ER models add inheritance to entity types -- superclasses and subclasses. Subclasses inherit all the attributes of their superclass(es).

Subclasses can:

- be *disjoint* or *overlapping*;
- represent *total* or *partial* specialization.

** University Member

Consider this model of a university member:

#+BEGIN_CENTER
#+ATTR_LaTeX: :height .6\textheight
[[file:er-univ-member.pdf]]
#+END_CENTER

- Do faculty members have a major?
- Do students have a rank or salary?

** Employee and Student Subclasses

Here we break the UNIV_MEMBER into two subtypes:

#+BEGIN_CENTER
#+ATTR_LaTeX: :height .5\textheight
[[file:eer-employee-student.pdf]]
#+END_CENTER

Notice that the subclasses are overlapping, as denoted by the O in the circle under UNIV_MEMBER. That means that an entity can be both a STUDENT and an EMPLOYEE.

But there's more:

- What's that Emp_type attribute?
- Can an emplyee have a salary and a number of hours?

** Faculty and Staff Subclasses

***                                                           :BMCOL:B_block:
    :PROPERTIES:
    :BEAMER_env: block
    :BEAMER_col: 0.5
    :END:

[[file:eer-faculty-staff.pdf]]

***                                                           :BMCOL:B_block:
    :PROPERTIES:
    :BEAMER_env: block
    :BEAMER_col: 0.5
    :END:

- The subclasses of EMPLOYEE are disjoint (D in the circle) -- an employee is either SALARIED or HOURLY but not both.
- The double line from employee means *total specialization* -- there are no EMPLOYEE instances, only SALARIED or HOURLY.

The process of going from an entity type that has attributes that don't apply to all entity instances to subclasses that are specialized but inherit the common attributes is called *specialization* (top-down).[fn:1]

[fn:1] We're not quite done, but we'll return to this example.

** Cars and Trucks

Let's consider another model.

#+BEGIN_CENTER
#+ATTR_LaTeX: :height .6\textheight
[[file:er-car-truck.pdf]]
#+END_CENTER

Notice the common attributes. We can factor those into a superclass.

** Vehicles

The common attributes are in the superclass and the specialized attributes are in the subclass.

#+BEGIN_CENTER
#+ATTR_LaTeX: :height .6\textheight
[[file:eer-vehicle.pdf]]
#+END_CENTER

The process of factoring the common attributes of two or more entity types and creating superclasses to hold the common attributes is called *generalization* (bottom-up).

** Student Employees

Remember our STUDENT - EMPLOYEE hierarchy:

#+BEGIN_CENTER
#+ATTR_LaTeX: :height .7\textheight
[[file:eer-faculty-staff.pdf]]
#+END_CENTER

What about STUDENTS who are also HOURLY employees, like TAs and research assistants?

** Multiple Inheritance

Our previous EER models have been inheritance trees -- each subclass had only one superclass. We can create lattices with multiple inheritance:

#+BEGIN_CENTER
#+ATTR_LaTeX: :height .7\textheight
[[file:eer-faculty-staff-student-employee.pdf]]
#+END_CENTER

** Fin

Subclassses provide for more granular and precise modeling of entity types. Use sublcasses when:

- you want to represent commonality and differences between different entity types,
- you want to have different subsets of an enity type participate in different relationships (e.g., faculty participate in TEACHES relationships, HOURLY employees don't).
