#+TITLE: Introduction to Logic
#+AUTHOR:
#+EMAIL:
#+DATE:
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS: H:2 toc:nil
#+BEAMER_FRAME_LEVEL: 2
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [smaller]
#+LaTeX_HEADER: \usepackage{verbatim, multicol, tabularx}
#+LaTeX_HEADER: \usepackage{sourcecodepro}
#+LaTeX_HEADER: \usepackage[T1]{fontenc}
#+LaTeX_HEADER: \usepackage{amsmath,amsthm, amssymb, latexsym, listings, qtree}
#+LaTeX_HEADER: \lstset{extendedchars=\true, inputencoding=utf8, frame=tb, aboveskip=1mm, belowskip=0mm, showstringspaces=false, columns=flexible, basicstyle={\footnotesize\ttfamily}, numbers=left, frame=single, breaklines=true, breakatwhitespace=true, tabsize=4,  keywordstyle=\color{blue}, identifierstyle=\color{violet}, stringstyle=\color{teal}, commentstyle=\color{darkgray}}
#+LaTeX_HEADER: \setbeamertemplate{footline}[frame number]
#+LaTeX_HEADER: \hypersetup{colorlinks=true,urlcolor=blue}
# #+LaTeX_HEADER: \logo{\includegraphics[height=.75cm]{GeorgiaTechLogo-black-gold.png}}

* Introduction to Logic

** Logic

A foundational branch of mathematics (the other foundation is set theory) that deals with the assignment of truth values to statements, also called *deduction* or *proof*.

- Statements, a.k.a., sentences, are either true, false, or neither.
- Propositions are either true or false.
- Axioms are propositions that are assumed to be true.  Consider them the starting rules of a system.

Example:

Assuming the axioms of standard arithmetic,

- $x + 5 = 7$ is a statement if we don't know the value of $x$
- If we know the value of $x$, $x + 5 = 7$ is a proposition.  In particular:
  - $x + 5 = 7$ is *true* if $x = 2$, and
  - $x + 5 = 7$ is *false* if $x \ne 2$

** Proofs

- Proofs are chains of statements that lead from axioms to a final statement, called a conclusion, such that if each statement in the proof is true, the conclusion must be true.



*** Truth :B_alertblock:
:PROPERTIES:
:BEAMER_env: alertblock
:END:

Mathematical logic does not deal with the meaning of truth.  It only deals with the systematic treatment of true and false statements.  The meaning of truth is a matter for philosophy.

** Theorems

- Theorems are statements that have been proved.
  - We usually use /theorem/ to refer to major results in mathematics.
- Lemmas are theorems that are useful primarily in proving other theorems.
- Corrollaries are theorems that follow "quickly" (one or two deduction steps) from a theorem.

** Example: Context-free Grammars

Consider the following system of axioms:

- $S \rightarrow aSb$
- $S \rightarrow \epsilon$, where $\epsilon$ means empty string

The set of axioms above is in instance of a /grammar/.  A grammar is

- a set of /terminal symbols/, which can be an /alphabet/ (a.k.a. /lexicon/) or set of words; here $\{a, b\}$,
- a set of /nonterminal symbols/ which act as syntactic vairables in the grammar; here $\{S\}$,
- a distinguished nonterminal that acts as the start symbol; here $S$, and
- a set of axioms of the form $\alpha \rightarrow \beta$, called /production/ or /grammar/ rules.

A /context-free grammar/ contains production rules with only nonterminals on the left.

** Example: Language Generation

A production rule says that the symbol on the left can be replaced by the sequence of symbols on the right.  A sequence of subsititions consitutes a /proof/ that the final sequence of symbols, the conclusion, is a sentence in the language specified by the grammar.  For example


| $S$     | the start symbol                         |
| $aSb$   | by Rule 1, $S \rightarrow aSb$           |
| $aaSbb$ | by Rule 1, $S \rightarrow aSb$           |
| $aabb$  | by Rule 2, $S \rightarrow \epsilon$      |

is a proof that the sequence of symbols, or /string/, $aabb$ is a sentence of the language, generated by successive applications of axioms, or production rules, in the language's grammar.

*** Parsing                                                                                       :B_alertblock:
:PROPERTIES:
:BEAMER_env: alertblock
:END:

The opposite problem, determining whether a given string is a valid sentence in a language, can be solved by finding a sequence of production rules that produce the string.  This sequence of production rules can be represented as a tree, called a /parse tree/, and the program that does this is called a /parser/.  A parser is an essential component of language analyzers such as interpreters and compilers.

** Truth Functionals

An assignment of true or false to a new proposition is *truth functional* if the assignment is made based on the truth of related propositions, and the validity of the logical connectives linking the component propositions to the new proposition.  In other words, the truth of a proposition is a /function/ of the truth values of logically related propositions.

** Logical Connectives

A *connective* is a word that connects two sentences to form a new sentence.  For example:

- Roses are red *and* violets are blue.
- You win *or* you lose.
-

Logical connectives, or logical operators, connect propositions to create new propositions.
